package edu.vassar.cmpu203.obre.model;
import android.content.Context;

import org.json.JSONException;
import org.junit.Test;
import org.junit.runner.RunWith;

import android.graphics.Bitmap;
import android.graphics.BitmapFactory;

import androidx.test.ext.junit.runners.AndroidJUnit4;
import androidx.test.platform.app.InstrumentationRegistry;

import java.io.IOException;
import java.io.InputStream;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.TimeUnit;
import static org.junit.Assert.*;


/**
 * Instrumented test for the {@link LLMAlgo} class, which runs on an Android device.
 */
@RunWith(AndroidJUnit4.class)
public class LLMAlgoTest {

    /**
     * Tests a real network call to the Gemini API using the method.
     * <p>
     * This test performs the following steps:
     * 1. Loads a test image (`bottle.jpg`) from the test assets folder.
     * 2. Creates an {@link LLMAlgo} instance.
     * 3. Calls the `sendImageToGemini` method with the loaded bitmap.
     * 4. Asserts that the API call completed successfully without errors.
     * 5. Asserts that the received response text is not null or empty.
     *
     * @throws InterruptedException if the thread is interrupted while waiting for the latch.
     * @throws IOException if the test image asset cannot be opened or read.
     */
    @Test
    public void testGeminiRealCall() throws InterruptedException, IOException, JSONException {
        LLMAlgo llm = new LLMAlgo();

        // Use getContext() to access the test app's assets folder
        Context context = InstrumentationRegistry.getInstrumentation().getContext();
        InputStream is = context.getAssets().open("bottle.jpg");
        Bitmap bitmap = BitmapFactory.decodeStream(is);
        is.close();

        CountDownLatch latch = new CountDownLatch(1);
        final String[] resultHolder = new String[1];
        final Exception[] errorHolder = new Exception[1];

        llm.sendImageToGemini(bitmap, new LLMAlgo.Listener() {
            /**
             * Handles the successful response from the Gemini API.
             * @param responseText The text generated by the model.
             */
            @Override
            public void onSuccess(String responseText) {
                resultHolder[0] = responseText;
                latch.countDown();
            }

            /**
             * Handles any errors that occur during the API call.
             * @param e The exception that occurred.
             */
            @Override
            public void onError(Exception e) {
                errorHolder[0] = e;
                e.printStackTrace();
                latch.countDown();
            }
        });

        // Wait for callback (timeout after 30 seconds)
        boolean completed = latch.await(30, TimeUnit.SECONDS);
        assertTrue("Callback did not fire within 30 seconds", completed);

        // Assert no error occurred
        assertNull("API call returned an error", errorHolder[0]);

        // Assert we got a response
        assertNotNull("Response should not be null", resultHolder[0]);
        assertFalse("Response should not be empty", resultHolder[0].isEmpty());

        // Optional: print response for debugging
        System.out.println("Gemini Response: " + resultHolder[0]);
    }
}