package edu.vassar.cmpu203.obre.view;

import android.os.Bundle;
import android.util.TypedValue;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.fragment.app.Fragment;

import edu.vassar.cmpu203.obre.R;
import edu.vassar.cmpu203.obre.databinding.FragmentUploadImageBinding;
import edu.vassar.cmpu203.obre.databinding.FragmentResultBinding;

public class ResultFragment extends Fragment implements ResultUI {

    private static final String ARG_RESULT_TEXT = "result_text";
    private String resultText;
    private Listener listener;
    private FragmentResultBinding binding;


    /**
     * Fragment used to display the textual results returned by the AI model.
     */
    public ResultFragment() {
    }

    /**
     * Factory method/Constructor to create a new instance with the result text.
     *
     * @param resultText The text generated by the AI to display.
     */
    public ResultFragment(String resultText) {
        Bundle args = new Bundle();
        args.putString(ARG_RESULT_TEXT, resultText);
        setArguments(args);
    }

    @Override
    public void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        if (getArguments() != null) {
            resultText = getArguments().getString(ARG_RESULT_TEXT);
        }
    }

    @Override
    public View onCreateView(@NonNull LayoutInflater inflater, @Nullable ViewGroup container,
                             @Nullable Bundle savedInstanceState) {
        // Inflate a simple layout for result display
        return inflater.inflate(R.layout.fragment_result, container, false);
    }

    @Override
    public void onViewCreated(@NonNull View view, @Nullable Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);

        LinearLayout ll = view.findViewById(R.id.scroll_layout);

        TextView tv = new TextView(getContext());
        tv.setText(resultText != null ? resultText : "No result");
        tv.setTextSize(TypedValue.COMPLEX_UNIT_SP, 24f);
        ll.addView(tv);

        // Optional: you can add a back button here if you want
        view.findViewById(R.id.back_button).setOnClickListener(v -> {
                    this.listener.onSwitchToUpload(resultText);
                    requireActivity().getSupportFragmentManager().popBackStack();
                }
        );
    }

    @Override
    public void setListener(Listener listener) {
        this.listener = listener;
    }
}
