package edu.vassar.cmpu203.obre.model;

import android.annotation.SuppressLint;
import android.content.Context;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.net.Uri;

import androidx.annotation.NonNull;
import androidx.annotation.OptIn;

import com.google.common.util.concurrent.FutureCallback;
import com.google.common.util.concurrent.Futures;
import com.google.common.util.concurrent.ListenableFuture;
import com.google.firebase.ai.FirebaseAI;
import com.google.firebase.ai.GenerativeModel;
import com.google.firebase.ai.java.GenerativeModelFutures;
import com.google.firebase.ai.type.Content;
import com.google.firebase.ai.type.GenerateContentResponse;
import com.google.firebase.ai.type.GenerativeBackend;
import com.google.common.util.concurrent.FutureCallback;
import com.google.common.util.concurrent.Futures;

import org.opencv.core.Mat;

import java.io.InputStream;
import java.util.Collections;
import java.util.List;
import java.util.concurrent.Executors;

import edu.vassar.cmpu203.obre.BuildConfig;
import kotlinx.serialization.ExperimentalSerializationApi;

/**
 * A class to handle interactions with the LLM, sending image data and receiving a response.
 */
public class LLMAlgo implements MediaAlgo{

    String apiKey;

    @Override
    public List<DetectedObject> runOnFrame(Mat frame) {
        return Collections.emptyList();
    }

    /**
     * An interface for callbacks to handle the asynchronous response from the LLM.
     */
    public interface Listener {
        /**
         * Called when the LLM successfully returns a response.
         * @param responseText The text generated by the model.
         */
        void onSuccess(String responseText);

        /**
         * Called when an error occurs during the LLM call.
         * @param e The exception that occurred.
         */
        void onError(Exception e);
    }

    /**
     * Constructs a new LLMAlgo instance.
     */
    public LLMAlgo() {
        apiKey = BuildConfig.GOOGLE_API_KEY;
    }

    /**
     * Creates a Bitmap object from a given content URI.
     * @param context The application context.
     * @param uri The URI of the image.
     * @return A Bitmap object, or null if the URI cannot be resolved into a bitmap.
     */
    public static Bitmap bitmapFromUri(Context context, Uri uri) {
        try {
            InputStream inputStream = context.getContentResolver().openInputStream(uri);
            if (inputStream == null) return null;
            return BitmapFactory.decodeStream(inputStream);
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

    /**
     * sends the provided bitmap image to the Gemini model for analysis.
     * The model's response or any error is returned through the provided listener.
     * @param bitmap The image to be analyzed.
     * @param listener The callback to handle the asynchronous response.
     */
    @OptIn(markerClass = ExperimentalSerializationApi.class)
    @SuppressLint("RestrictedApi")
    public void sendImageToGemini(Bitmap bitmap, Listener listener) {

        GenerativeModel firebaseAI = FirebaseAI.getInstance(GenerativeBackend.googleAI())
                .generativeModel("gemini-2.5-flash");

        GenerativeModelFutures model = GenerativeModelFutures.from(firebaseAI);
        //Bitmap bitmap = bitmapFromUri(context, uri);

        if (bitmap == null) {
            listener.onError(new Exception("Could not decode bitmap from URI."));
            return;
        }

        Content content = new Content.Builder()
                .addImage(bitmap)
                .addText("Describe what is in this image for a visually impaired person. 5 - 20 words")
                .build();

        ListenableFuture<GenerateContentResponse> response = model.generateContent(content);

        Futures.addCallback(response, new FutureCallback<GenerateContentResponse>() {
            @Override
            public void onSuccess(GenerateContentResponse result) {
                String resultText = result.getText();
                listener.onSuccess(resultText);  // Call listener
            }

            @Override
            public void onFailure(@NonNull Throwable t) {
                t.printStackTrace();
                listener.onError((Exception) t);  // Call listener on error
            }
        }, Executors.newSingleThreadExecutor());
    }
}



